#!/usr/bin/env ruby

#
# YOU NEED TO USE API_CALLER SUCH AS:
#
# ./api_caller scripts/*.script
#

script_path = ARGV[0]
CONFIG_PATH = "config"

abort "script path is missing"              unless script_path
abort "file does not exist: #{script_path}" unless File.exist?(script_path)
abort "config file missing"                 unless File.exist?(CONFIG_PATH)

def config
  lines = File.open(CONFIG_PATH, "r").each_line.to_a
  lines.map{ |line| line.split("=").map(&:chomp) }.flatten
end

config_hash = Hash[*(config)]
skey        = config_hash["skey"]
script_body = File.read(script_path).gsub("$skey", skey)

puts "-------------------------"
puts "[Command]\n"
script_body.lines.each do |line|
  puts line unless line.start_with?("#")
end
puts "-------------------------"

system script_body
