#!/usr/bin/env ruby

require 'slack-notifier'
#
# author: Kei Sugano <tobasojyo@gmail.com>
#
#
# XXX send slack notification
#
# YOU NEED TO GENERATE WEBHOOK URL WITH THE FOLLOWING INSTRUCTION:
# https://get.slack.help/hc/en-us/articles/115005265063-Incoming-WebHooks-for-Slack
#

CONFIG_PATH = "slacker/config"

def guide_config(config)
  unless File.exist?(config)
    File.open(config, "w") do |f|
      f.puts("webhook_url=[your webhook url]")
    end
    abort("\nYou need to edit file: #{config}\n\n")
  end
end

def parse_config(config)
  guide_config(CONFIG_PATH)
  array = File.read(config).split("\n").map { |line|
    line.split("=")      
  }.flatten
  Hash[*array]
end

config_hash = parse_config(CONFIG_PATH)

notifier = Slack::Notifier.new(config_hash["webhook_url"]) 
message  = "charge.created"
notifier.ping message
