#!/usr/bin/env ruby

#      March 2018       
# Su Mo Tu We Th Fr Sa  
#              1  2  3  
#  4  5  6  7  8  9 10  
# 11 12 13 14[15]16 17  
# 18 19 20 21 22 23 24  
# 25 26 27 28 29 30 31  
#
# This means the days_remained is 17.
# Supposed that the customer is going to be charged with
# 2000 yen...
#
# FOR THE INTENSION TO MAKE IT RECOGNIZABLE TO
# JAPANESE DEVELOPERS, THE TERM "HIWARI" IS USED
# WHICH MEANS CHARGE PER DAY.
#

require 'date'

def assert(expected, real)
  if expected != real
    abort("expected: #{expected}, real: #{real}")
  end
end

users_sign_in_date     = Date.new(2018, 3, 15)
days_in_month_of_march = 31
charge_amount          = 2000
customer_id            = "cust_test_5b4vkgkeal49aafdo2k"
skey                   = ARGV[0]

days_remained          = days_in_month_of_march - users_sign_in_date.day + 1
assert 17, days_remained

hiwari_amount_total = days_remained * charge_amount
assert 34000, hiwari_amount_total

curl_command = "curl -s https://api.omise.co/charges \\\n" \
               "  -X POST \\\n" \
               "  -u #{skey}: \\\n" \
               "  -d \"amount=#{hiwari_amount_total}\" \\\n" \
               "  -d \"currency=jpy\" \\\n" \
               "  -d \"customer=#{customer_id}\""

#
# YOU WANT TO EXECUTE THE FOLLOWING COMMAND:
#
puts curl_command
